// rock-react/src/components/input-components/check-code-input/check-code-input.component.js
import React, { Component } from "react";
import PropTypes from "prop-types";

import { Subject, Observable } from 'rxjs';

import _times from "lodash/times";
import _random from "lodash/random";

import CheckCodeService from "../../../services/checkcode.service.js";

import "./check-code-input.component.css";

const propTypes = {
  placeholder: PropTypes.string,
  phoneOrEmail: PropTypes.string
};

const defaultProps = {
  placeholder: "请输入验证码.."
};

class CheckCodeInputComponent extends Component {
  constructor(props) {

    super(props);

    this.state = {
      placeholder: this.props.placeholder,
      checkCodeSign: this.getCheckCodeSign(),
      checkNewSign: null,                   // 通过图片验证后返回的新签名
      timerCount: 10,                       // 默认倒计时时间
      checkcodeTimeButtonText: null,        // 
      defaultStep: "pre_send_click",        // pre_send_click, clicked_send_click, clicked_checkcode
      checkcodeInvalid: null,              // 针对图片验证码是否通过的标识
      checkcodeIsValid: null,              // 针对手机或邮件验证码是否通过的标识 
      phoneOrEmailInValid: true,            // 针对手机或邮箱格式是否正确的标识   
    };

    this.changeCheckCodeImage = this.changeCheckCodeImage.bind(this);
    this.onCheckCodeChange = this.onCheckCodeChange.bind(this);
    this.onCheckCheckCode = this.onCheckCheckCode.bind(this);
  }

  componentWillReceiveProps(nextProps) {

    this.setState({
      phoneOrEmailInValid: nextProps.phoneOrEmail !== '18500183080'
    });

  }

  componentDidUpdate(nextProps, nextState) {
    return true; // or true;
  }

  changeSteps(step) {
    this.setState({
      defaultStep: step
    });
  }

  changeCheckCodeImage() {
    this.setState({
      checkCodeSign: this.getCheckCodeSign()
    });
  }

  getCheckCodeSign() {
    return _times(48, () => _random(35).toString(36)).join("");
  }

  onCheckCodeChange(event) {
    // console.log(event.target.value, "onCheckCodeChange");
  }

  onValidateCheckCode() {
    alert(this.checkCodeInput.value);
  }

  onCheckCheckCode(event) {

    const code = event.keyCode || event.which;

    if (code !== 13 || this.checkCodeInput.value.trim().length == 0) {
      return;
    }

    if (this.state.checkcodeInvalid !== null && !this.state.checkcodeInvalid) {
      this.onValidateCheckCode();
      return;
    }

    // check checkCode
    // post http://52.192.42.233:8081/checkcode

    CheckCodeService.checkCheckCode({
      checkcode: this.checkCodeInput.value,
      checktype: "image",
      receiver: this.props.phoneOrEmail,
      sign: this.state.checkCodeSign
    }).then(result => {

      let good = false;

      if (result.code === 200) {
        good = true;
      }
      
      this.setState({
        checkcodeInvalid: !good,
        placeholder: good ? "验证码已发送" : this.props.placeholder,
        checkNewSign: good ? result.data.sign : null,
        timerCount: good ? result.data.seconds : this.state.timerCount
      });

      if (!good) {
        return;
      }

      this.runTimerInterval();
      this.changeSteps('clicked_checkcode') ;
      this.checkCodeInput.value = null;

    });
  }

  retry() {
    
    if (this.state.interval) clearInterval(this.state.interval);

    this.setState({
      checkcodeInvalid: null,
      placeholder: this.props.placeholder,
      checkNewSign: null,
      timerCount: 10
    });

    this.changeSteps("clicked_send_click");
    this.changeCheckCodeImage();

  }

  runTimerInterval() {
    this.runInterval(() => {
      this.setState({
        checkcodeTimeButtonText: this.getTimeStr(this.state.timerCount)
      });
    }, () => {
      this.setState({
        timerCount: this.state.timerCount - 1
      });
    }, () => {
      return this.state.timerCount <= 0;
    });

  }

  runInterval(func, prefunc, stop) {

    func();

    this.state.interval = setInterval(() => {
      if (prefunc) prefunc();
      if (stop()) clearInterval(this.state.interval);
      func();
    } , 1000);

  }

  getTimeStr(timeCount) {
    const s = timeCount.toString().length === 1 ? '0' + timeCount : timeCount;
    
    return (<span style={{fontSize: '.825em'}}>倒计时 <b style={{display:'inline-block', width: '22px',fontSize: '1.5em'}}> {s} </b> 秒</span>);

  }

  render() {

    const { placeholder, phoneOrEmail, watch } = this.props;

    // watch(phoneOrEmail, (newPhoneOrEmail) => {
    //     console.log(newPhoneOrEmail, 'newPhoneOrEmail');
    // });

    return (
      <div className="check-code-input-component input-group">
      
        <span
          className="input-group-label"
          style={{ padding: "0 .425rem", color: "black" }}
        >
          <i className="material-icons">&#xE8CE;</i>
        </span>
        <input
          className={
            "input-group-field " +
            (this.state.checkcodeInvalid ? "checkcode-invalid" : "")
          }
          type="text"
          pattern="[a-z0-9]{1,15}"
          disabled={ this.state.phoneOrEmailInValid }
          ref={input => (this.checkCodeInput = input)}
          onChange={this.onCheckCodeChange}
          onKeyDown={this.onCheckCheckCode}
          placeholder={this.state.placeholder}
          id="check_code"
          name="check_code"
          required
        />

        <input type="hidden" id="check_code_sign" name="check_code_sign" />
        <input
          type="hidden"
          id="validate_code_sign"
          name="validate_code_sign"
        />

        <span
          className={"input-group-label " + (this.state.phoneOrEmailInValid ? "checkcode-disable-button" : "")}
          onClick={() => this.changeSteps("clicked_send_click")}
          style={{
            cursor: "pointer",
            padding: "0 .425rem",
            color: "blueviolet",
            borderLeft: "none",
            backgroundColor: "antiquewhite",
            display:
              this.state.defaultStep === "pre_send_click" ? "flex" : "none"
          }}
        >
          发送验证码
        </span>
        <span
          className="input-group-label checkcode "
          onClick={this.changeCheckCodeImage}
          style={{
            width: "104px",
            borderLeft: "none",
            backgroundSize: "100% 100%",
            display:
              this.state.defaultStep === "clicked_send_click" ? "flex" : "none",
            backgroundImage:
              'url("' +
              "/checkcode?sign=" +
              this.state.checkCodeSign +
              "&receiver=18500183080" +
              '")'
          }}
        />
        <span
          className="input-group-label checkcode-valid-button checkcode-correct"
          onClick={() => this.onValidateCheckCode() }
          style={{ borderLeft: "none", display: this.state.checkcodeInvalid === null || this.state.checkcodeInvalid ? "none" : "flex" }}
        >
        验证
        </span>
        <span
          className="input-group-label checkcode-valid-button"
          onClick={() => this.retry()}
          style={{ width: "auto", borderLeft: "none", display: this.state.checkcodeInvalid === null || this.state.checkcodeInvalid ? "none" : "flex" }}
        >
          重试
        </span>
        <span
          className="input-group-label checkcode-time-button"
          style={{ display: this.state.checkcodeInvalid === null || this.state.checkcodeInvalid ? "none" : "flex" }}
        >
          {this.state.checkcodeTimeButtonText}
        </span>
      </div>
    );
  }
}

CheckCodeInputComponent.propTypes = propTypes;
CheckCodeInputComponent.defaultProps = defaultProps;

export default CheckCodeInputComponent;

// angular2/src/app/component/check-code-input/check-code-input.component.ts
import { AfterViewInit, Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import * as _ from 'lodash';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/from';
import 'rxjs/add/observable/interval';
import { CheckcodeService } from '../../_services/_index';

@Component({
  selector: 'app-check-code-input',
  templateUrl: './check-code-input.component.html',
  styleUrls: ['./check-code-input.component.css']
})
export class CheckCodeInputComponent implements OnInit, AfterViewInit {

  @Input()
  isDisable: Boolean;

  @Input()
  phoneOrEmail: any;

  checkCodeValue: any;

  steps: String = 'pre_send_click';       // clicked_send_click
  placeholder: String = '请输入验证码';
  checkCodeSrc: String ;
  checkcodeInvalid: Boolean = false;
  checkCodeLength: Number = 6;
  timerCount: any = 10;
  checkcodeTimeButtonText: String;
  checkCodeSign: String;
  checkNewSign: String;             // 通过图片验证之后，服务器会返回一个新的sign, 拿着这个新的sign去服务器验证用户收到的短信验证码(或邮件验证码)
  isValidate: boolean;
  timer: any;

  @Output()
  checkCodeChange = new EventEmitter<string>();

  @Input()
  get checkCode(){
    return this.checkCodeValue;
  }

  set checkCode(val) {
    this.checkCodeValue = val;
    this.checkCodeChange.emit(this.checkCodeValue);
  }

  constructor(private checkcodeService: CheckcodeService) {

  }

  ngOnInit() {
    this.setCheckcodeTimeButtonText(this.getTimeStr(this.timerCount));
  }

  ngAfterViewInit() {

  }

  setCheckcodeTimeButtonText(text: String): void {
    this.checkcodeTimeButtonText = text;
  }

  getTimeStr(timeCount: Number): String {
    const s = timeCount.toString().length === 1 ? '0' + timeCount : timeCount;
    return '倒计时' + s + '秒';
  }

  changeSteps(val: String): void {

    if (val === 'clicked_send_click') {
      this.changeCode();
      this.placeholder = '请输入图形验证码';
    }

    if (val === 'pre_send_click' || val === 'clicked_checkcode') {
      this.placeholder = '请输入验证码';
    }

    this.steps = val;

  }

  changeCode(): void {
    this.checkCodeSign = this.randomStr();
    this.checkCodeSrc = '/checkcode?sign=' + this.checkCodeSign + '&receiver=' + this.phoneOrEmail;
  }

  resendCode(): void {

    if (this.timer !== null || this.isValidate) {
      return;
    }

    this.changeSteps('clicked_send_click');
    this.changeCode();
    this.checkcodeInvalid = false;
    this.checkCode = null;
    this.isValidate = null;
  }

  validateCheckCode(): void {

    this.isValidate = null;

    if (this.checkNewSign && this.checkCode) {

      this.checkcodeService.check(this.checkNewSign, this.checkCode, this.phoneOrEmail).subscribe(result => {

        if (result.code !== 200) {
          this.validateFailed();
          return;
        }

        this.validateSuccess();

      });

    } else {
      this.validateFailed();
    }

  }

  validateFailed(): void {
    this.isValidate = false;
    this.checkcodeInvalid = true;
  }

  validateSuccess(): void {

    this.isValidate = true;
    this.checkcodeInvalid = false;
    this.setCheckcodeTimeButtonText('验证成功');

    if (this.timer != null) {
      this.timer.unsubscribe();
      this.timer = null;
    }
  }

  randomStr(): String {
    return _.times(48, () => _.random(35).toString(36)).join('');
  }

  onKeyup(event): void {

    if ( this.steps === 'clicked_send_click') {

      if (this.checkCodeValue.length >= this.checkCodeLength) {

        if (this.checkCodeValue.length > this.checkCodeLength) {
          this.checkcodeInvalid = true;
          return;
        }

        if (this.checkCodeValue.length === this.checkCodeLength) {
          this.checkCodeCheck();
        }
      }

    }

  }

  checkCodeCheck(): void {

    this.checkcodeInvalid = false;

    this.checkcodeService.check(this.checkCodeSign, this.checkCodeValue, this.phoneOrEmail).subscribe(result => {

      if (result.code === 200) {

        // good and get new sign
        this.checkNewSign = result.data.sign;

        if (result.data.seconds) {
          this.timerCount = result.data.seconds;
        }

        this.steps = 'clicked_checkcode';
        this.checkCode = null;
        this.placeholder = '已发送, 请输入验证码';
        this.setCheckcodeTimeButtonText(this.getTimeStr(this.timerCount));

        this.timer = Observable.interval(1000).subscribe((v) => {

          this.setCheckcodeTimeButtonText(this.getTimeStr(this.timerCount - v - 1));

          if (this.timerCount - v <= 0) {
            this.timer.unsubscribe();
            this.timer = null;
            this.setCheckcodeTimeButtonText('重新发送');
          }

        });

      } else {
        // bad
        // invalide checkcode
        this.checkNewSign = null;
        this.checkcodeInvalid = true;
      }
    });

  }

  onKeydown(event): void {

    const code = event.keyCode || event.which;

    if ( this.steps === 'clicked_send_click' && this.checkCodeValue && this.checkCodeValue.length >= this.checkCodeLength) {

      // 8: back, 37: left arrow
      if (code === 8 || code === 37 || code === 39) {
        return;
      }

      event.preventDefault();

    }

  }

}

<div class="input-group">
  <span class="input-group-label" style="padding: 0 .425rem;color:black;">
    <i class="material-icons">&#xE8CE;</i>
  </span>
  <input class="input-group-field checkcode-invalid" type="text" [disabled]="isDisable"
         [ngClass]="{'checkcode-invalid': checkcodeInvalid}"
         (keyup)="onKeyup($event)"
         (keydown)="onKeydown($event)"
         placeholder="{{placeholder}}" [(ngModel)]="checkCode" id="check_code" name="check_code" required>
  <span (click)="changeSteps('clicked_send_click')" *ngIf="steps==='pre_send_click'"
        class="input-group-label"
        [ngClass]="{'checkcode-disable-button': isDisable}"
        style="cursor: pointer; padding: 0 .425rem;color: blueviolet;background-color: antiquewhite;">
        发送验证码
  </span>
  <span (click)="changeCode()" *ngIf="steps==='clicked_send_click'"
        class="input-group-label checkcode "
        [style.background-image]="'url(' + checkCodeSrc + ')'">

  </span>
  <span (click)="validateCheckCode()" *ngIf="steps==='clicked_checkcode'"
        class="input-group-label checkcode-valid-button checkcode-correct"
        [ngClass]="{'checkcode-correct': isValidate != null && isValidate,
                    'checkcode-wrong': isValidate != null && !isValidate,
                    'checkcode-disable-button': isDisable || !(checkCode && checkCode.trim().length > 3 && checkCode.trim().length < 8) }">
        &ensp;验证&ensp;
  </span>
  <span *ngIf="steps==='clicked_checkcode'"
        (click)="resendCode()"
        class="input-group-label checkcode-time-button"
        [ngClass]="{'checkcode-disable-button': isDisable}">
        <i>{{checkcodeTimeButtonText}}</i>
  </span>
</div>
