// rock-react/src/components/signup/signup.component.js
import React, { Component } from "react";
import PropTypes from "prop-types";


import CheckCodeInputComponent from '../input-components/check-code-input/check-code-input.component';

import './signup.component.css';

const propTypes = {
  message: PropTypes.string.isRequired,
  onClick: PropTypes.func
};

const defaultProps = {
  content: "default Content here"
};

class SignupComponent extends Component {
  componentWillMount() {
    console.log("componentWillMount");
  }

  componentDidMount() {
    console.log("componentDidMount");
  }

  componentWillUpdate(prevProps, prevState) {
    console.log(
      this.props,
      this.state,
      prevProps,
      prevState,
      "componentWillUpdated"
    );
  }

  shouldComponentUpdate(nextProps, nextState) {
    console.log(
      this.props,
      this.state,
      nextProps,
      nextState,
      "shouldComponentUpdate"
    );
    return true; // or true;
  }

  constructor(props) {

    super(props);

    this.state = {
      title: "Sign up Component",
      phoneOrEmail: null
    };

    this.onSubmit = this.onSubmit.bind(this);
    this.onPhoneOrEmailChange = this.onPhoneOrEmailChange.bind(this);

  }

  onSubmit(event) {
    event.preventDefault();

    console.log(this.userName.value, 'this.userName');
    console.log(this.passwd.value, 'this.passwd');
    console.log(this.phoneOrEmail.value, 'this.phoneOrEmail');
  }

  onPhoneOrEmailChange(event) {

    this.setState({ 
      phoneOrEmail: event.target.value
    });
  }

  render() {
    const { message, onClick, content } = this.props;

    return (
      <div className="signup-component-wapper">
        <div className="signup-component">
          <div style={{display: 'none'}}>
            {this.state.title}, {message},
            <a href="javascript:void(this)" onClick={onClick}>
              Click Me
            </a>,
            {content || defaultProps.content}
          </div>

          <span className="flash-message" style={{display: 'none'}}>注册失败</span>

          <div className="form-container signup-component">
            <h5 style={{textAlign: 'left',fontWeight: 'bold', fontSize: '.8em',color: 'dimgray'}}>
              农资经营者管理软件
            </h5>

            <div className="input-group">
                <img style={{width: '25px', height: '25px', marginRight: '.425em'}} src="/assets/images/chuhe-logo.png" />
              <span style={{lineHeight: '25px'}}>新用户注册</span>
            </div>


            <form onSubmit={this.onSubmit} id="signup-form" action="/registry" method="POST">

              <div className="input-group">
                <span className="input-group-label" style={{padding: '0 .425rem', color: 'black'}}>
                  <i className="material-icons">&#xE8D3;</i>
                </span>
                <input className="input-group-field" type="text"  ref={input => this.userName = input}
                  placeholder="请输入用户名或邮箱地址" id="user_name" name="user_name" required />
              </div>

              <div className="input-group">
                <span className="input-group-label" style={{padding: '0 .425rem', color: 'black'}}>
                  <i className="material-icons">&#xE897;</i>
                </span>
                <input className="input-group-field" type="password" ref={input => this.passwd = input}
                  placeholder="请输入密码" id="user_passwd" name="user_passwd" required />
              </div>

              <div className="input-group">
                <span className="input-group-label" style={{padding: '0 .425rem', color:'black'}}>
                  <i className="material-icons">&#xE0CD;</i>
                </span>
                <input className="input-group-field" type="text" ref={input => this.phoneOrEmail = input}
                  onChange={this.onPhoneOrEmailChange}
                  placeholder="请输入手机号码或电子邮箱地址" id="user_phone" name="user_phone" required />
              </div>

              <CheckCodeInputComponent phoneOrEmail={ this.state.phoneOrEmail } placeholder={'请输入验证码'} />

              <div style={{textAlign: 'right', fontSize: '.9em'}}>
                <a href="/login">登录</a>
                <span className="split">&Iota;</span>
                <a href="javascript:void(this);">忘记密码!</a>
              </div>

              <div style={{textAlign: 'left', marginTop: '1em', marginBottom: '2em'}}>
                <button style={{marginBottom: '0'}} type="submit"
                        className="basic-btn button">立即注册</button>
              </div>

            </form>

          </div>
        </div>
      </div>
    );
  }
}

SignupComponent.propTypes = propTypes;
SignupComponent.defaultProps = defaultProps;

export default SignupComponent;

// angular2/src/app/_components/signup/signup.component.ts

import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';

import * as $ from 'jquery';

import {fallIn, moveIn, comp} from '../../routers/router.animations';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
  animations: [ comp() ],
  host: { '[@comp]': '' }
})
export class SignupComponent implements OnInit {

  state: String = '';
  error: any;

  username: String = '';
  passwd: String = '';
  phone: String = '';
  checkCode: any;
  address: String = '';
  isAgreeRule: Boolean = false;

  constructor(private http: HttpClient, private router: Router ) {

  }

  onSubmit(formData) {

    if (!formData.valid) {
      return;
    }

    $('.signup-component #signup-form').submit();


    // validate user
    // curl -v -l -H "Content-type: application/json" \
    // -X POST -d '{"username":"tongtong","password":"Cc"}' http://localhost:8844/login

    // need to setup a proxy to backend

    /*const req = this.http.post('/login', {
      username: formData.controls.email._value,
      password: formData.controls.password._value
    }).subscribe(
      res => {
        console.log(res);

        window.location.href = '/index';
      },
      (err: HttpErrorResponse) => {
        if (err.error instanceof Error) {
          console.log(err.message, 'Client-side Error Occured');
        } else {
          console.log(err.message, ' #Server-side Error Occured');
        }
      }
    ); */

    return;

    // if (formData.controls.email._value !== 'chunhui2001@gmail.com') {
    //   this.error = 'Invalid email formatter';
    //   return;
    // }
    //
    // this.router.navigateByUrl('/members');

  }

  ngOnInit() {

  }

}

<div class="form-container signup-component">


  <h5 style="text-align: left;font-weight: bold;    font-size: .8em;color: dimgray;">
    农资经营者管理软件
  </h5>

  <div class="input-group">
      <img style="width: 25px; height: 25px;margin-right: .425em;" src="/assets/images/chuhe-logo.png" />
    <span style="line-height: 25px;">新用户注册</span>
  </div>

  <span class="error" *ngIf="error" [@fallIn]="state">{{ error }}</span>

  <form id="signup-form" #formData="ngForm"  action="/registry" method="POST">

    <div class="input-group">
      <span class="input-group-label" style="padding: 0 .425rem;color:black;">
        <i class="material-icons">&#xE8D3;</i>
      </span>
      <input class="input-group-field" type="text"
        placeholder="请输入用户名或邮箱地址" [(ngModel)]="username" id="user_name" name="user_name" required />
    </div>


    <div class="input-group">
      <span class="input-group-label" style="padding: 0 .425rem;color:black;">
        <i class="material-icons">&#xE897;</i>
      </span>
      <input class="input-group-field" type="password"
        placeholder="请输入密码" [(ngModel)]="passwd" id="user_passwd" name="user_passwd" required>
    </div>


    <div class="input-group">
      <span class="input-group-label" style="padding: 0 .425rem;color:black;">
        <i class="material-icons">&#xE0CD;</i>
      </span>
      <input #check_input_element class="input-group-field" type="text"
        placeholder="请输入手机号码" [(ngModel)]="phone" id="user_phone" name="user_phone" required>
    </div>

    <app-check-code-input #check_code_input [(checkCode)]="checkCode"
                          [isDisable]=" !phone || phone.length === 0 "
                          [check_input_element]="check_input_element"
                          [(phoneOrEmail)]="phone"></app-check-code-input>

    <div class="input-group">
      <span class="input-group-label" style="padding: 0 .425rem;color:black;">
        <i class="material-icons">&#xE88A;</i>
      </span>
      <input class="input-group-field" type="text"
        placeholder="请输入联系地址" [(ngModel)]="address" id="home_address" name="home_address">
    </div>


    <div style="text-align: right;font-size: .9em;">
      <a href="/login">登录</a>
      <span style="color: gray;">&Iota;</span>
      <a href="javascript:void(this);">忘记密码!</a>
    </div>

    <div style="text-align: left;font-size: .9em;margin-top: 1em;">
      <mat-checkbox [checked]="isAgreeRule" (change)="isAgreeRule = !isAgreeRule">
        同意 <a href="javascript:void(this);" style="font-weight: bold;">"服务条款"</a> 和
        <a href="javascript:void(this);" style="font-weight: bold;">"隐私权相关政策"</a></mat-checkbox>
    </div>

    <div style="text-align: left;    margin-top: 1em;margin-bottom: 2em;">
	    <button style="margin-bottom: 0;" type="submit" [disabled]="!(formData.valid && isAgreeRule)"
              (click)="onSubmit(formData)"
	            class="basic-btn button">立即注册</button>
  	</div>

  </form>

</div>
